### ISSUE TITLE
Error getting social proof message on homepage

### ISSUE THREAD

**Issue by suniblestephen** [dhanur/Sunible-Beta#53] opened 2013-07-10 16:42 UTC

**Comment by ghost** [comment] 2013-07-10 16:46
There is an old file out there with outdated db info.  I'll take care of
this right now and purge it from the master branch.  It keeps reappearing
and causes this problem.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by ghost** [comment] 2013-07-10 16:56
Root Cause:  vars_db.php contained incorrect database access parameters.  every time there was a push to production, the incorrect parameters were transferred from master.

Fix:  vars_db.php master file updated with correct db data.  future production pushes will now use the correct data.

**Closed as completed by ghost** 2013-07-10 16:56 UTC
Labels: bug, emergency
