### ISSUE TITLE
Footer Links on Sunible.com are off the screen

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#27] opened 2013-06-19 02:39 UTC
When I visit Sunible.com, I can't see the footer links. I need to scroll down to view them. This is a problem since new users don't know its there.

**Comment by ghost** [comment] 2013-06-19 08:44
This is a formatting issue that I'll have Roman look at.  I had to increase
the page length because on Stephen's browser the Button was cut off.  The
effect of doing that however is that for most browsers/resolutions, it
pushed the links off the page as you noted.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment] 2013-06-19 08:53
This is a huge usability issue John, can we reduce the page length or whatever's needed to bring this back?

In order to solve a minor issue on the installer page, we're creating a major issue for our entire rest of the site :)

We can't have risk any homeowner missing the footer links, which is highly likely right now.
On June 19, 2013 at 1:44:01 AM, John Bissell (notifications@github.com) wrote:
This is a formatting issue that I'll have Roman look at. I had to increase  
the page length because on Stephen's browser the Button was cut off. The  
effect of doing that however is that for most browsers/resolutions, it  
pushed the links off the page as you noted.  

John Bissell  
CTO  

Solar Simplified  

Cell: (510) 229-0577  
Skype: john.bissell  
Email: john@sunible.com  

55 Harrison Street, 3rd Floor  
Oakland, CA 94607

**Comment by ghost** [comment] 2013-06-19 09:01
We can reduce the page length, but then the Submit button on Stephen's
computer (he must use a lower screen resolution) runs off the page and
disappears.  He can't even progress to the next page.

The links bottom formatting is "relative" in that they always appear at the
bottom of the existing page.  I could set to "absolute" and fix the problem
for you, but in Stephen's case the links may show up in the middle of the
page text.

I'll ask Roman to look at this after the Safari issue.  We need the links
to appear just below the Submit Button on each page - they should be
relative to the button, not the page.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment] 2013-06-19 09:05
Got it.

By "the Submit button on Stephen's computer (he must use a lower screen resolution) runs off the page and 
disappears" .. did you mean the Submit button on the Installer Onboarding page or Sunible.com landing page?

On June 19, 2013 at 2:01:59 AM, John Bissell (notifications@github.com) wrote:
We can reduce the page length, but then the Submit button on Stephen's  
computer (he must use a lower screen resolution) runs off the page and  
disappears. He can't even progress to the next page.  

The links bottom formatting is "relative" in that they always appear at the  
bottom of the existing page. I could set to "absolute" and fix the problem  
for you, but in Stephen's case the links may show up in the middle of the  
page text.  

I'll ask Roman to look at this after the Safari issue. We need the links  
to appear just below the Submit Button on each page - they should be  
relative to the button, not the page.  

John Bissell  
CTO  

Solar Simplified  

Cell: (510) 229-0577  
Skype: john.bissell  
Email: john@sunible.com  

55 Harrison Street, 3rd Floor  
Oakland, CA 94607

**Comment by ghost** [comment] 2013-06-19 09:09
Sunible.com landing page.  It very well may be happening on the Installer
site as well because I used the same code base.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment] 2013-06-28 20:50
John, is Roman working on fixing this?

**Comment by ghost** [comment] 2013-06-28 21:13
Next bug up.  The first was the Safari issue fix  which I just pushed to
production.  I can't test - can you refresh your cache and give it a shot
and let me know....

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by suniblestephen** [comment] 2013-06-28 21:28
Same problem at 2:27pm PS

On Fri, Jun 28, 2013 at 2:13 PM, John Bissell notifications@github.comwrote:

> Next bug up. The first was the Safari issue fix which I just pushed to
> production. I can't test - can you refresh your cache and give it a shot
> and let me know....
> 
> John Bissell
> CTO
> 
> Solar Simplified
> 
> Cell: (510) 229-0577
> Skype: john.bissell
> Email: john@sunible.com
> 
> 55 Harrison Street, 3rd Floor
> Oakland, CA 94607
> 
> On Fri, Jun 28, 2013 at 1:50 PM, dhanur notifications@github.com wrote:
> 
> > John, is Roman working on fixing this?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/solarisbetter/beta/issues/27#issuecomment-20213540>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/27#issuecomment-20214752
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by rlytvynchuk** [comment] 2013-06-29 19:55
issue fixed

**Comment by svlasenko** [comment] 2013-07-01 19:49
I verified this issue in "beta" trunk but we have a new issue #33 after fix

**Comment by svlasenko** [comment] 2013-07-04 19:35
It's reproducible on master and trunk.

**Comment by rlytvynchuk** [comment] 2013-07-07 08:45
issue fixed for trunk. Assigned to QA.

To fix it in Master we need to decide whether old version of page should stay or new, created by John in his branch.

If old -> we merge current version from trunk to branch
If new -> John merges his code to trunk, you test it and merge to master

**Comment by svlasenko** [comment] 2013-07-08 17:03
Verified in Master branch

**Closed as completed by svlasenko** 2013-07-08 17:03 UTC
Labels: bug, QA
